name: Scraping Laptop Data

on:
  schedule:
    # This cron expression means "every day at 12:00 PM UTC" (3:00 PM Ethiopian time)
    - cron: '0 12 * * *'  # 3:00 PM Ethiopian Time = 12:00 PM UTC
  workflow_dispatch:  # Allows manual triggering from GitHub UI

permissions:
  contents: write  # Ensure the GitHub token has write access to repository contents

jobs:
  scraping:
    runs-on: ubuntu-latest  # Runs on the latest Ubuntu image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # This checks out your repo to the runner

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.1'  # Specify the version of Python

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Install all libraries in requirements.txt

      - name: Run scraper script
        run: |
          python3 scripts/dagilaptopspages.py  # Run the laptop scraper script

      - name: Commit and push updated CSV file
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Ensure the output directory exists
          mkdir -p web-scraping/ecommerce  # Ensure the directory exists (just in case)

          # Add the updated CSV file to the commit
          git add web-scraping/ecommerce/dagi_laptops_multiple_pages.csv
          
          # Commit the changes if any
          git commit -m "Update laptop listings data with new highlights"

          # Push the changes to the remote repo
          git push https://x-access-token:${{ secrets.MY_PAT }}@github.com/rexxgit/web-scraping.git
        env:
          MY_PAT: ${{ secrets.MY_PAT }}  # Use the Personal Access Token stored in GitHub secrets
