name: data

on:
  schedule:
    - cron: '0 9 * * *'  # Adjust to your desired schedule
  workflow_dispatch:  # Allow manual triggering from the GitHub UI

permissions:
  contents: write  # Required for pushing changes to the repository

jobs:
  scraping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Install Playwright and Chromium
        run: |
          pip install playwright
          playwright install chromium

      - name: Run scraper script
        run: |
          python3 scripts/data.py

      - name: Commit and push scraped data
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add web-scraping/ecommerce/project
          git commit -m "Update scraped data"
          git push https://x-access-token:${{ secrets.MY_PAT }}@github.com/rexxgit/web-scraping.git
        env:
          MY_PAT: ${{ secrets.MY_PAT }}
