name: Web Scraping

on:
  schedule:
    # Cron expression for running the script at 5:00 PM UTC every day,
    # which is 8:00 PM Ethiopian Time (EAT)
    - cron: '0 17 * * *'
  workflow_dispatch:  # Allows manual triggering from GitHub UI

permissions:
  contents: write  # Ensure the GitHub token has write access to repository contents

jobs:
  scraping:
    runs-on: ubuntu-latest  # Runs on the latest Ubuntu image

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3  # This checks out your repo to the runner

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.1'  # Specify the version of Python

      # Step 3: Install dependencies
        run: |
          pip install -r requirements.txt  # Install all libraries in requirements.txt

      # Step 4: Run the scraping script located in /scripts/scrape1.py
      - name: Run scraping script
        run: python scripts/scrape1.py  # Point to the correct script path

      # Step 5: Commit and push scraped data to the repository
      - name: Commit and push scraped data
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add web-scraping/ecommerce/addisber.com(food-items,instant-foods).csv  # Adjust the path to your output file
          git commit -m "Update scraped data"
          git push https://x-access-token:${{ secrets.MY_PAT }}@github.com/rexxgit/web-scraping.git
        env:
          MY_PAT: ${{ secrets.MY_PAT }}  # Use a Personal Access Token stored in GitHub secrets
