name: Web Scraping

on:
  schedule:
    # This cron expression means "every day at 6 AM UTC"
    - cron: '0 6 * * *'
    # This cron expression means "every day at 9 AM UTC"
    - cron: '0 9 * * *'
    # This cron expression means "every Monday at 3 PM UTC"
    - cron: '0 15 * * 1'
    # This cron expression means "every Wednesday at 12 PM UTC"
    - cron: '0 12 * * 3'
    # This cron expression means "every Friday at 5 PM UTC"
    - cron: '0 17 * * 5'
  workflow_dispatch:  # Allows manual triggering from GitHub UI

permissions:
  contents: write  # Ensure the GitHub token has write access to repository contents

jobs:
  # Job 1: Scrape Script 1
  scrape1:
    runs-on: ubuntu-latest  # Runs on the latest Ubuntu image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.1'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Install Playwright and Chromium
        run: |
          python -m pip install playwright
          python -m playwright install chromium

      - name: Run scraper script 1
        run: python scrape1.py  # Run the first script

      - name: Commit and push data from script 1
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add ecommerce/output1.csv  # Adjust this path as needed
          git commit -m "Update data from scrape1"
          git push https://x-access-token:${{ secrets.MY_PAT }}@github.com/rexxgit/web-scraping.git
        env:
          MY_PAT: ${{ secrets.MY_PAT }}

  # Job 2: Scrape Script 2
  scrape2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.1'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Install Playwright and Chromium
        run: |
          python -m pip install playwright
          python -m playwright install chromium

      - name: Run scraper script 2
        run: python scrape2.py  # Run the second script

      - name: Commit and push data from script 2
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add ecommerce/output2.csv  # Adjust this path as needed
          git commit -m "Update data from scrape2"
          git push https://x-access-token:${{ secrets.MY_PAT }}@github.com/rexxgit/web-scraping.git
        env:
          MY_PAT: ${{ secrets.MY_PAT }}

  # Job 3: Scrape Script 3
  scrape3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.1'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Install Playwright and Chromium
        run: |
          python -m pip install playwright
          python -m playwright install chromium

      - name: Run scraper script 3
        run: python scrape3.py  # Run the third script

      - name: Commit and push data from script 3
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add ecommerce/output3.csv  # Adjust this path as needed
          git commit -m "Update data from scrape3"
          git push https://x-access-token:${{ secrets.MY_PAT }}@github.com/rexxgit/web-scraping.git
        env:
          MY_PAT: ${{ secrets.MY_PAT }}

  # Job 4: Scrape Script 4
  scrape4:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.1'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Install Playwright and Chromium
        run: |
          python -m pip install playwright
          python -m playwright install chromium

      - name: Run scraper script 4
        run: python scrape4.py  # Run the fourth script

      - name: Commit and push data from script 4
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add ecommerce/output4.csv  # Adjust this path as needed
          git commit -m "Update data from scrape4"
          git push https://x-access-token:${{ secrets.MY_PAT }}@github.com/rexxgit/web-scraping.git
        env:
          MY_PAT: ${{ secrets.MY_PAT }}

  # Job 5: Scrape Script 5
  scrape5:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.1'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Install Playwright and Chromium
        run: |
          python -m pip install playwright
          python -m playwright install chromium

      - name: Run scraper script 5
        run: python scrape5.py  # Run the fifth script

      - name: Commit and push data from script 5
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add ecommerce/output5.csv  # Adjust this path as needed
          git commit -m "Update data from scrape5"
          git push https://x-access-token:${{ secrets.MY_PAT }}@github.com/rexxgit/web-scraping.git
        env:
          MY_PAT: ${{ secrets.MY_PAT }}
