name: Web Scraping

on:
  schedule:
    # This cron expression means "every day at 6 AM UTC"
    - cron: '0 6 * * *'
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  scraping:
    runs-on: ubuntu-latest  # Runs on the latest Ubuntu image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # This checks out your repo to the runner

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.1'  # Specify the version of Python

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Install all libraries in requirements.txt

      - name: Install Playwright and Chromium
        run: |
          python -m playwright install chromium  # Install Chromium for Playwright (if you need it)

      - name: Run scraper script
        run: python scrape.py  # Replace with your script file name

      - name: Save output to ecommerce directory
        run: |
          mkdir -p ./ecommerce  # Create the ecommerce directory if it doesn't exist
          mv ./data/output.csv ./ecommerce/output.csv  # Move the output CSV file to ecommerce/ directory
