name: Web Scraping

on:
  schedule:
    # This cron expression means "every day at 6 AM UTC"
    - cron: '0 6 * * *'
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  scraping:
    runs-on: ubuntu-latest  # Runs on the latest Ubuntu image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # This checks out your repo to the runner

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.1'  # Specify the version of Python

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Install all libraries in requirements.txt

      - name: Install Playwright and Chromium (Optional)
        run: |
          python -m playwright install chromium  # Install Chromium for Playwright (if needed)

      - name: Run scraper script
        run: python scrape.py  # Run the script that generates the output.csv

      # This step is not necessary for pushing the changes back to the repo
      # Remove commit and push part if not needed
