name: Web Scraping

on:
  schedule:
    # This cron expression means "every day at 6 AM UTC"
    - cron: '0 6 * * *'
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  scraping:
    runs-on: ubuntu-latest  # Runs on the latest Ubuntu image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # This checks out your repo to the runner

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.1'  # Specify the version of Python

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Install all libraries in requirements.txt

      - name: Install Playwright and Chromium (Optional)
        run: |
          python -m playwright install chromium  # Install Chromium for Playwright (if needed)

      - name: Run scraper script
        env:
          MY_PAT: ${{ secrets.MY_PAT }}  # Use the PAT stored in GitHub Secrets
        run: |
          python scrape.py  # Run the script that generates the output.csv

      # Optional: Push the results back to the repository
      - name: Commit and push scraped data
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add ecommerce/output.csv
          git commit -m "Update scraped data"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub's automatic token for pushing changes
