name: Web Scraping

on:
  schedule:
    # This cron expression means "every day at 8:30 PM Ethiopian time (UTC+3)"
    - cron: '30 17 * * *'  # This runs the action at 8:30 PM Ethiopian Time (UTC+3)
  workflow_dispatch:  # Allows manual triggering from GitHub UI

permissions:
  contents: write  # Ensure the GitHub token has write access to repository contents

jobs:
  scraping:
    runs-on: ubuntu-latest  # Runs on the latest Ubuntu image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # This checks out your repo to the runner

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.1'  # Specify the version of Python

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Install all libraries in requirements.txt

      - name: Install Playwright and Chromium (Optional)
        run: |
          python -m playwright install chromium  # Install Chromium for Playwright (if needed)

      - name: Run scraper script
        run: python scripts/scrape1.py  # Run the script that generates the output.csv

      - name: Commit and push scraped data
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add "web-scraping/ecommerce/addisber.com_food-items_instant-foods.csv"  # Updated file name without parentheses
          git commit -m "Update scraped data"
          git push https://x-access-token:${{ secrets.MY_PAT }}@github.com/rexxgit/web-scraping.git
        env:
          MY_PAT: ${{ secrets.MY_PAT }}  # Use the Personal Access Token stored in GitHub secrets
