name: Web Scraping

on:
  schedule:
    # This cron expression means "every day at 9:35 PM Ethiopian time (UTC +3)"
    - cron: '35 18 * * *'  # Run at 9:35 PM EAT (6:35 PM UTC)
  workflow_dispatch:  # Allows manual triggering from GitHub UI

permissions:
  contents: write  # Ensure the GitHub token has write access to repository contents

jobs:
  scraping:
    runs-on: ubuntu-latest  # Runs on the latest Ubuntu image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # This checks out your repo to the runner

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.1'  # Specify the version of Python

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Install all libraries in requirements.txt

      - name: Run scraper script
        run: |
          python3 scripts/scrape1.py  # Run the scraper script

      - name: Commit and push scraped data
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Ensure the ecommerce directory or specific file is added to Git
          git add web-scraping/ecommerce/addisber.com_food-items_instant-foods.csv
          
          # Commit the changes
          git commit -m "Update scraped data"
          
          # Push the changes to the remote repo
          git push https://x-access-token:${{ secrets.MY_PAT }}@github.com/rexxgit/web-scraping.git
        env:
          MY_PAT: ${{ secrets.MY_PAT }}  # Use the Personal Access Token stored in GitHub secrets
